### PR TITLE
Adding the caching-microprofile prototype

### PR DESCRIPTION
**Pull request by evelinec**
This PR has the `caching-microprofile` application prototype. 

- The `caching-mciroprofile` application is to replace the existing `hazelcast-microprofile` microserivce, as it contains the more extensive MicroProfile microservices. Detail of this application can be found in the `README.adoc` or  the`README.html`, which is a generated version of the adoc content. 

- The application is also placed in the directory structure to be consistent with the Open Liberty guides' [Structure and Styles](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles). For example, the complete code are located in the `finish` directory. Building the cache data in microservices steps can be developed and put in the `start` directory. 

- The `README.adoc` has the outline of the guide. Each session needs to be further written in paragraphs.

### CODE REVIEW

**Comment by enozcan** [comment]
Hi @evelinec 

Thanks for your contribution.
Since this repo contains the code belonging to a published content I cannot merge your PR into this. However I will complete the missing parts you mentioned and send another PR to your repo or OpenLiberty/guides repo directly. I will inform you soon.

**Comment by evelinec** [comment]
Hi @enozcan, sounds good. Thank you.

**Comment by enozcan** [comment]
Hi @evelinec 

I've just completed your guide. Will you open a repo under OpenLiberty or should I send a PR to your own repo?

**Comment by evelinec** [comment]
Hi @enozcan, can you create a PR to my own repo pls? Thank you.

**Comment by evelinec** [comment]
Hi @enozcan, thank you for creating the PR. We've added some review feedback [here](https://github.com/evelinec/caching-microprofile-microservices-on-kubernetes/pull/1). Let us know if you have any questions.

**Comment by enozcan** [comment]
Hi @evelinec 
Since I will continue to complete the guide [here](https://github.com/evelinec/caching-microprofile-microservices-on-kubernetes/pull/1) I'm closing that PR.
Thanks for the contribution

**Pull request closed without merging**
